### ISSUE TITLE
sigma nought values in S1 netCDF files are wrong

### ISSUE THREAD

**Issue by CatherineTaelman** [CryosphereVirtualLab/public-notebooks#10]
I have been playing around a bit with S1 data in the netCDF format (accessed via opendap and xarray). There seems to be an issue with the sigma nought values provided in the files, because they are not the actual image data but just a (linearly?) increasing grid. See my script here: https://github.com/CatherineTaelman/public-notebooks/blob/main/plot_s1_scene.ipynb.  I first plot amplitude (for HH channel), which looks good. Afterwards I plot sigma nought values (also for HH channel), but that is obviously not the actual image data.. Is this a known issue?

**Comment by ykern** [comment]
Thanks for your question. It looks like the sigma nought is a calibration matrix that needs to be applied to the amplitude values (probably through array multiplication?). 
I am not familiar with sigma nought but checked with Mikhail. He said that one would usually expect that these coefficients are a subset that is interpolated to measurement grid at runtime and not a full array like in this case. So maybe that was what you expected?

**Comment by steingod** [comment]
Yes, these bands are the sigma0 tables, band maths according to the information under Application of Radiometric Calibration LUT https://sentinels.copernicus.eu/web/sentinel/radiometric-calibration-of-level-1-products.

**Comment by CatherineTaelman** [comment]
Oh okay, yes that makes sense indeed. Thanks a lot for the clarification!
