### ISSUE TITLE
bounding box seach in CVL

### ISSUE THREAD

**Issue by CatherineTaelman** [CryosphereVirtualLab/public-notebooks#8]
The current bounding box search on the CVL platform is fixed to return only datasets that are entirely within the search box (Current filter: Within). This is very inconvenient when searching for satellite imagery, since the footprints of these images are very large and the current setup does not return a result if the full image is not within the bounding box. It would be nice if the bounding box search had an option to choose whether it should return all subset results (filter=within) or all intersecting results (filter=intersect).

**Comment by ykern** [comment]
Thanks for the good suggestion and sorry for the late answer. We have taken this information further and will get back with information as soon as we know more.

**Comment by steingod** [comment]
We will implement this. Will probably in available in a couple of weeks along with some other features.

**Comment by steingod** [comment]
This is now available in the search interface. You can decide on the type of bounding box, and there are some other updates to the interface as well. We have tested this quite thoroughly, but if you discover issues on certain browsers, please open a new issue on that so we can dig into it.

**Comment by ykern** [comment]
Great work, thanks a lot for the efforts! I'll close this issue now. Please reopen or raise a new issue if follow up is needed.

**Comment by CatherineTaelman** [comment]
Seems to work well on Firefox. Thanks for implementing this!
