### ISSUE TITLE
met.no server down

### ISSUE THREAD

**Issue by CatherineTaelman** [CryosphereVirtualLab/public-notebooks#9]
The met.no Thredds server seems to be down for at least the last 24 hours already. Error message when I try to download/access Sentinel data through the CVL interface: '503 Service Temporarily Unavailable'. Error message that appears in my script when trying to acces the netCDF file on the server: 
![Screenshot from 2022-11-22 10-33-36](https://user-images.githubusercontent.com/48383489/203546772-b250c280-10c3-4456-b4f2-dd5652809268.png)

**Comment by ykern** [comment]
Thanks for the message. When I access the following link on a browser it seems to work: https://nbstds.met.no/thredds/catalog/NBS/S1A/2022/11/18/EW/catalog.html?dataset=nbs/S1A/2022/11/18/EW/S1A_EW_GRDM_1SDH_20221118T082018_20221118T082124_045946_057F7D_3F6D.nc

So maybe this is something related to the CVL interface.
Can you set up a merge request so I could have a look at your script or provide the code section from the script you are using here?

**Comment by steingod** [comment]
We had a major issue in the disk systems and it took time before all subsystems, including TDS came up again. This was announced in a number of channels, but I apologise as we forgot to publish this information on CVL.

**Comment by CatherineTaelman** [comment]
okay I see, everything is working again this morning!
